version: '3.7'

services:
 jenkins:
    build: .
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=password
      - IP_SERVER=206.189.88.120
      - CASC_JENKINS_CONFIG=/var/jenkins_conf
    container_name: jenkins
    privileged : yes
    user : root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins:/var/jenkins_home
      - ./config:/var/jenkins_conf
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    restart: unless-stopped
